ldap:
  url: ldap://server.DOMAIN.local:389
  domain: DOMAIN.local
  base: OU=UserFolder,DC=DOMAIN,DC=local
  adminRoles:
spring:
  r2dbc:
    url: r2dbc:postgresql://pg-server-addr:5432/pass_storage
    username: postgres
    password:
  flyway:
    url: jdbc:postgresql://pg-server-addr:5432/pass_storage
server:
  port: 8080
#debug: true