ldap:
  url: ldap://ARBIS-NEW.local:389
  domain: ARBIS-NEW.local
  base: OU=Office,DC=ARBIS-NEW,DC=local
  adminRoles:
    - File Exchange Users
    - Администраторы домена
spring:
  r2dbc:
    url: "r2dbc:postgresql://arb-pg-1c-prod:5432/pass-storage"
    username: "postgres"
    password: "5556360"

